# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OPTileLoaderDialog
                                 A QGIS plugin
 Load Mars and The Moon basemaps
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-29
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Robermaps
        email                : robermaps@outlook.es
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import Qt

from . import basemaps, datasets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'optileloader_dialog_base.ui'))


class OPTileLoaderDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(OPTileLoaderDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.basemapTree, self.addBasemap = self._setup_tab(
            self.tabBasemaps, basemaps.BODIES, basemaps.BASEMAPS, basemaps.info_url)
        self.datasetTree, self.addDataset = self._setup_tab(
            self.tabDatasets, datasets.BODIES, datasets.DATASETS, datasets.info_url)

    def _setup_tab(self, tab, bodies, entries, info_url):
        """Fill a tab with a tree of entries grouped by body and an add button.

        :returns: the tree and the add button.
        """
        layout = QtWidgets.QVBoxLayout(tab)

        tree = QtWidgets.QTreeWidget()
        tree.setHeaderHidden(True)
        for body, title in bodies:
            parent = QtWidgets.QTreeWidgetItem([self.tr(title)])
            parent.setFlags(Qt.ItemFlag.ItemIsEnabled)
            tree.addTopLevelItem(parent)
            for key, entry in entries.items():
                if entry['body'] != body:
                    continue
                item = QtWidgets.QTreeWidgetItem([entry['name']])
                item.setData(0, Qt.ItemDataRole.UserRole, key)
                tip = info_url(key)
                if entry.get('draft'):
                    tip = self.tr('Draft / preliminary basemap') + '\n' + tip
                item.setToolTip(0, tip)
                parent.addChild(item)
            parent.setExpanded(True)
        layout.addWidget(tree)

        button = QtWidgets.QPushButton(self.tr('Add to QGIS'))
        button.setEnabled(False)
        layout.addWidget(button)

        tree.itemSelectionChanged.connect(
            lambda: button.setEnabled(self._selected_key(tree) is not None))
        tree.itemDoubleClicked.connect(lambda *args: button.click())
        return tree, button

    @staticmethod
    def _selected_key(tree):
        items = tree.selectedItems()
        return items[0].data(0, Qt.ItemDataRole.UserRole) if items else None

    def selected_basemap(self):
        """Key of the selected basemap, or None if a body header or nothing is selected."""
        return self._selected_key(self.basemapTree)

    def selected_dataset(self):
        """Key of the selected dataset, or None if a body header or nothing is selected."""
        return self._selected_key(self.datasetTree)
